### ISSUE TITLE
Test reporter hangs on async tests

### ISSUE THREAD

**Issue by fhartwig** [owickstrom/purescript-spec-mocha#1]
When I use the mocha test reporter to run a test like the following

```
main = run [mochaReporter] do
    describe "do something" do
        it "successfully does something" do
            liftEff $ log "hello"
            res <- later' 100 $ return "Alligator"
            liftEff $ log "good bye"
            return unit
```

, the test page just hangs showing `passes: 0 failures: 0 duration: 0s`. If I comment out the line containing `later'`, everything works and the test success is shown. In either case the second log message is shown in the console.

(I apologise if this is expected behaviour / a user error. I'm new to purescript and js programming in general.)

**Comment by owickstrom** [comment]
Thanks for reporting! I'll look into this as soon as possible. :)

**Comment by owickstrom** [comment]
OK, I know what's the issue here and it's the implementation of the Mocha reporter together with how reporters work in purescript-spec. Working on it now. :)

**Comment by fisx** [comment]
any news on this?   i may have time to contribute code to this, and changes will improve if you can fill us in on what you already know.  thanks!  (-:

**Comment by owickstrom** [comment]
Oh, sorry for dropping the ball on this one. Have been short on time lately, but I got somewhere with this on the `async-reporter` branch: https://github.com/owickstrom/purescript-spec/tree/async-reporter

It does not compile but I think it's nearly there. The idea is to change from having a fully collected test result tree which the reporters can use, to let reporters await tests themselves. 

``` purescript
-- Previously:
type Reporter e = Array Group -> Eff e Unit
-- Now:
type Reporter e = Array (Group (Aff e Unit)) -> Aff e Unit
```

This way the mocha reporter can call the underlying `it`, `describe` etc synchronously and run the `done` callback asynchronously.

If you have the time to look at this and perhaps finish the stuff that I started that would be very helpful! :) I'd love to get some more people involved in this project.

By the way, this could be affected by https://github.com/owickstrom/purescript-spec/issues/16, the suggestion for a Free monad implementation of purescript-spec to support selective runs of test (skip, only).

**Comment by fisx** [comment]
ok, thanks!  i should be able to work with that.  now it's my turn to drop the ball.  but i'll try not to!  give me a week or two-  (-:

**Comment by owickstrom** [comment]
No problem at all, I guess it's you folks that need this the most right now, and I'm just utterly grateful for all the help I can get. :+1:

**Comment by owickstrom** [comment]
A year later, and now this works. I got some energy for my PureScript projects and decided to fix this limitation. Use `purescript-spec` 0.10.0 and `purescript-spec-mocha` 0.2.0 (notice the name change).
