### ISSUE TITLE
Remove "forall e" quantifier in Mocha.purs

### ISSUE THREAD

**Issue by alvart** [owickstrom/purescript-spec-mocha#10]
At line 45 in src/Test/Spec/Mocha.purs:
```purescript
runMocha
  :: forall e
   . Spec Unit
 -> Effect Unit
```

`forall e` generates the following warning: 

> Type variable e is ambiguous, since it is unused in the polymorphic type which introduces it.

**Comment by alvart** [comment]
At line 45 in src/Test/Spec/Mocha.purs:
```purescript
runMocha
  :: forall e
   . Spec Unit
 -> Effect Unit
```

`forall e` generates the following warning: 

> Type variable e is ambiguous, since it is unused in the polymorphic type which introduces it.

**Comment by owickstrom** [comment]
No longer in there after #12. Thanks!
