### ISSUE TITLE
Tag a release for pre-aff 4.0?

### ISSUE THREAD

**Issue by anttih** [owickstrom/purescript-spec-mocha#6]
Could you tag a release for a766d7bf8c097ff9b54a6fc518f0055065490e2c so I can add this to the current package-set?

**Comment by owickstrom** [comment]
Yeah, sure. There's now a v1.0.0 for that commit (https://pursuit.purescript.org/packages/purescript-spec-mocha/1.0.0) and v2.0.0 for current master.

**Comment by anttih** [comment]
Great, thanks!
