### ISSUE TITLE
Documentation about integrating this with existing Mocha tests

### ISSUE THREAD

**Issue by winstonwolff** [owickstrom/purescript-spec-mocha#7]
I had a hard time getting this to work with my existing set of non-Purescript specs. You might mention that the example exports a `main()` function which needs to be called by whatever requires/imports it into the rest of the tests.  E.g.:

```
// all_tests.js
require('my_javascriptspec');
{main) = require('my_purescript_spec');
main();
```

Maybe this is self-evident to those experienced with Purescript, but for someone just getting started with Purescript, it was unexpected.

**Comment by owickstrom** [comment]
Hi! I haven't seen this usage before, but yes, I think it should definitely be documented. And it is not self-evident at all, you need to know some fiddly details about how PureScript transpiles to Javascript to figure that out. 😄 

Would you like to send a PR with a sub-heading under "Usage" in the README? Thanks!

**Comment by winstonwolff** [comment]
Here's the PR: https://github.com/owickstrom/purescript-spec-mocha/pull/8
